### PR TITLE
fix D build, with D lang openssl 2.0.3

### PR DESCRIPTION
**Pull request by mingwugmail**
Fix D build failure:
https://github.com/D-Programming-Deimos/openssl/issues/63

thrift should be buildable with either openssl:
-- 1.1.6+1.0.1g
-- 2.0.3+1.1.0h

- [ ] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [ ] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [Y ] Did you squash your changes to a single commit?  (not required, but preferred)
- [ Y] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [ ] If your change does not involve any code, include `[skip ci]` anywhere in the commit message to free up build resources.

### CODE REVIEW

**Comment by mingwugmail** [comment]
BTW, I found I cannot log an issue on: https://github.com/apache/thrift

This makes the issue reporting and discussion difficult, can you enable issue report on https://github.com/apache/thrift ?

Thanks.

**Comment by Jens-G** [comment]
> I cannot log an issue on: https://github.com/apache/thrift

http://thrift.apache.org/docs/HowToContribute

**Comment by Jens-G** [comment]
```
src/thrift/internal/ssl.d(100): Error: static assert:  "Must have version either use_openssl_1_0_x or use_openssl_1_1_x defined, e.g.
	"subConfigurations": {
		"apache-thrift": "use_openssl_1_0"
	}"
Makefile:1292: recipe for target 'libthriftd-ssl.a' failed
make[4]: *** [libthriftd-ssl.a] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory '/thrift/src/lib/d'
Makefile:895: recipe for target 'all-recursive' failed
```

**Comment by mingwugmail** [comment]
@Jens-G 

I saw all the D test passing:

https://travis-ci.org/github/apache/thrift/jobs/772633220

```
====================
All 100 tests passed
====================
make[4]: Leaving directory '/thrift/src/lib/d'
make[3]: Leaving directory '/thrift/src/lib/d'
Making check in test
make[3]: Entering directory '/thrift/src/lib/d/test'
```

Not sure if other failure is related to D.

**Comment by mingwugmail** [comment]
@Jens-G Hi, why you close this PR? ) without this fix, it won't work with the latest openssl D binding 2.0.3 , as I noted here: https://github.com/D-Programming-Deimos/openssl/issues/63

**Comment by Jens-G** [comment]
>  closed this in 4abc5cf 9 minutes ago

You should read more carefully.

**Comment by mingwugmail** [comment]
(Sorry, I'm just a random user of Thrift, have no JIRA account, or on the dev mailing-list, not sure what's the best way to communicate with the core Thrift team. So I just add comments here, pls. bear with me; BTW I really think the git "issues" should be enabled for easy communication.)

My new question is: why the latest Python package is ~2 years ago:

https://pypi.org/project/thrift/#history
thrift 0.13.0 in Nov. 2019

and only unofficial package is 0.14.1:
https://pypi.org/project/thrift-unofficial/#history

Can the pip package update also be in the official release process?

Thanks.

**Comment by Jens-G** [comment]
> BTW I really think the git "issues" should be enabled for easy communication.)

What would be the benefit of maintaining two issue trackers just because one person (you) does not want to log in at JIRA?

**Comment by mingwugmail** [comment]
> > BTW I really think the git "issues" should be enabled for easy communication.)
> 
> What would be the benefit of maintaining two issue trackers just because one person (you) does not want to log in at JIRA?

I'm only one of the millions of github users who don't have JIRA account like me. 

If you open github issues here, I am sure there will be thousands of reports soon, for such popular projects like thrift, check grpc for example :

https://github.com/grpc/grpc/issues
