### PR TITLE
Add missing include for the security tests

### PR DESCRIPTION
**Pull request by tobim**
Fixes a build error on msvc that was introduced with #2760.

### CODE REVIEW

**Comment by tobim** [comment]
It looks like that didn't do the trick.
```
C:\projects\thrift\lib\cpp\test\SecurityFromBufferTest.cpp(202): error C2065: 'OPENSSL_VERSION_MAJOR': undeclared identifier [C:\projects\build\MSVC2017\x64\lib\cpp\test\SecurityFromBufferTest.vcxproj]
  Building Custom Rule C:/projects/thrift/lib/cpp/test/CMakeLists.txt
  SecurityTest.cpp
C:\projects\thrift\lib\cpp\test\SecurityTest.cpp(224): error C2065: 'OPENSSL_VERSION_MAJOR': undeclared identifier [C:\projects\build\MSVC2017\x64\lib\cpp\test\SecurityTest.vcxproj]
```
